name: project cicd flow

on:
  push:
    branches: 
      - feature
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install
   #sonarscan analysis 
    - name: Cache SonarQube packages
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build and analyze
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        mvn -B clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
        -Dsonar.projectKey=seema82_testsecurity \
        -Dsonar.organization=seema82 \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.java.binaries=target/classes
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push docker image
      uses: docker/build-push-action@v6
      with:
          context: .
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/springboot-java-image:${{github.ref_name}}
          #tags: seema85/springboot-java-image:latest
