name: project cicd flow

permissions:
  contents: read

on:
  push:
    branches: 
      - feature
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SONAR_HOST_URL: https://sonarcloud.io
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
      SONAR_ORGANIZATION: ${{ secrets.SONAR_ORG }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.sonar/cache
          ~/.m2
        key: ${{ runner.os }}-sonar-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-sonar-m2

    - name: Build with Maven
      run: mvn clean install

    - name: Build and analyze with SonarQube
      run: |
        mvn -B clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
        -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }} \
        -Dsonar.organization=${{ env.SONAR_ORGANIZATION }} \
        -Dsonar.host.url=${{ env.SONAR_HOST_URL }} \
        -Dsonar.login=${{ env.SONAR_TOKEN }} \
        -Dsonar.java.binaries=target/classes

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ env.DOCKERHUB_USERNAME }}/springboot-java-image:${{ github.ref_name }}

