
name: static code analysis
permissions:
  contents: read

on:    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SONAR_HOST_URL: https://sonarcloud.io
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
      SONAR_ORGANIZATION: ${{ secrets.SONAR_ORG }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
    - uses: actions/checkout@v4

    # Use Java 11 for Sonar plugin compatibility
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.sonar/cache
          ~/.m2
        key: ${{ runner.os }}-sonar-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-sonar-m2

    - name: Build and analyze
      run: |
        mvn -B clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
        -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }} \
        -Dsonar.organization=${{ env.SONAR_ORGANIZATION }} \
        -Dsonar.host.url=${{ env.SONAR_HOST_URL }} \
        -Dsonar.login=${{ env.SONAR_TOKEN }} \
        -Dsonar.java.binaries=target/classes
        
             


      


        
    
        
        

