name: project cicd flow

on:
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn clean install
     
    - name: SonarCloud Scan
      uses: SonarSource/sonarqube-scan-action@v4
      env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORG }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push docker image
      uses: docker/build-push-action@v6
      with:
          context: .
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/springboot-java-image:${{github.ref_name}}
          #tags: seema85/springboot-java-image:latest
